name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # change to your actual branch name if needed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install  # use npm ci only if you have package-lock.json

      - name: Build the React app
        run: npm run build

      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}